export const blogsData = [

    {
      id: 1,
      title: "Marketing Ideas",
      date: "May 24, 2018",
      author: "tufael4736@gmail.com",
      category: "uncategorized",
      bussiness: "business",
      image: "/Marketing-ideas.png",
    },
    {
      id: 2,
      title: "Rest During Working Hours",
      date: "June 10, 2018",
      author: "tufael4736@gmail.com",
      category: "uncategorized",
      bussiness: "business",   
      image: "/Rest-office.png",
    },
    {
      id: 3,
      title: "Develop Your Startup Idea",
      date: "July 02, 2018",
      author: "tufael4736@gmail.com",
      category: "uncategorized",
      bussiness: "business",
      image: "/startup-ideas.png",
    },
    {
      id: 4,
      title: "Travel and Work During Spring",
      date: "August 15, 2018",
      author: "tufael4736@gmail.com",
      category: "uncategorized",
      bussiness: "business",
      image: "/travelandwork.png",
    },
    {
      id: 5,
      title: "Plan Your Business",
      date: "September 01, 2018",
      author: "tufael4736@gmail.com",
      category: "uncategorized",
      bussiness: "business",
      image: "/plan-business.png",
    },
    {
      id: 6,  
      title: "Diversity in the Workplace",
      date: "October 20, 2018",
      author: "tufael4736@gmail.com",
      category: "uncategorized",
      bussiness: "business",
      image: "/diversity-PTZ4RGN-1400x788.png",
    },
    {
      id: 7,
      title: "Women in Business",
      date: "November 11, 2018",
      author: "tufael4736@gmail.com",
      category: "uncategorized",
      bussiness: "business",
      image: "/woman-business.png",
    },
    {
      id: 8,
      title: "Hardest Things in Programming",
      date: "December 05, 2018",
      author: "tufael4736@gmail.com",
      category: "uncategorized",
      bussiness: "business",
      image: "/hardest-things.png",
    },

]