// appliedJobsData.js
export const appliedJobsData = [
  {
    id: "1",
    title: "Project Manager",
    companyImage: "https://via.placeholder.com/150",
    companyName: "Sinotech Limited",
    location: "Dhaka (Banani)",
    salary: "Negotiable",
    deadline: "31 Dec 2025",
    status: "Applied",
  },
  {
    id: "2",
    title: "Senior Software Engineer",
    companyImage: "https://url-shortener.me/5QE5",
    companyName: "IlmiFyTech Agency",
    location: "Dhaka (Gulshan)",
    salary: "Negotiable",
    deadline: "15 Jan 2026",
    status: "Applied",
  },
  {
    id: "3",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    location: "Dhaka (Uttara)",
    salary: "Negotiable",
    deadline: "25 Jan 2026",
    status: "Applied",
  },
  {
    id: "4",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    location: "Dhaka (Uttara)",
    salary: "Negotiable",
    deadline: "25 Jan 2026",
    status: "Applied",
  },
  {
    id: "5",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    location: "Dhaka (Uttara)",
    salary: "Negotiable",
    deadline: "25 Jan 2026",
    status: "Applied",
  },
  {
    id: "6",
    title: "Project Manager",
    companyImage: "https://via.placeholder.com/150",
    companyName: "Sinotech Limited",
    location: "Dhaka (Banani)",
    salary: "Negotiable",
    deadline: "31 Dec 2025",
    status: "Applied",
  },
  {
    id: "7",
    title: "Senior Software Engineer",
    companyImage: "https://url-shortener.me/5QE5",
    companyName: "IlmiFyTech Agency",
    location: "Dhaka (Gulshan)",
    salary: "Negotiable",
    deadline: "15 Jan 2026",
    status: "Applied",
  },
  {
    id: "8",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    location: "Dhaka (Uttara)",
    salary: "Negotiable",
    deadline: "25 Jan 2026",
    status: "Applied",
  },
  {
    id: "9",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    location: "Dhaka (Uttara)",
    salary: "Negotiable",
    deadline: "25 Jan 2026",
    status: "Applied",
  },
  {
    id: "10",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    location: "Dhaka (Uttara)",
    salary: "Negotiable",
    deadline: "25 Jan 2026",
    status: "Applied",
  },
  
];
