export const projectsData = [
  {
    id: 1,
    image: "/assets/insurance_pic.jpg",
    title: "Insurance website for",
    author: "yas_som",
    type: "CMS",
    date: "10 december 2024",
  },
  {
    id: 2,
    image: "/assets/woman_pic.jpg",
    title: "AkiMed™ Science Website",
    author: "Harry Blaq",
    type: "CMS",
    date: "18 november 2024",
  },
  {
    id: 3,
    image: "/assets/store_design.jpg",
    title: "Hopes Promise Respite",
    author: "LLC Hopejekakye",
    type: "CMS",
    date: "02 october 2024",
  },
  {
    id: 4,
    image: "/assets/customtrading_pic.jpg",
    title: "Shopify Store Design",
    author: "CHARM",
    type: "CMS",
    date: "21 september 2024",
  },
  {
    id: 5,
    image: "/assets/custom-trading.jpg",
    title: "Custom Trading Website",
    author: "John",
    type: "Costum",
    date: "05 august 2024",
  },
  {
    id: 6,
    image: "/assets/shopping_pic.avif",
    title: "Custom E-Commerce",
    author: "Website Daneal",
    type: "Costum",
    date: "14 july 2024",
  },
  {
    id: 7,
    image: "/assets/tour_travel_pic.jpg",
    title: "Tour Travel Website",
    author: "Monalisa",
    type: "Costum",
    date: "30 june 2024",
  },
  {
    id: 8,
    image: "/assets/app_development.jpg",
    title: "Mobile App Development",
    author: "Mackkalam",
    type: "App",
    date: "11 may 2024",
  },
];
