import React from 'react';
export const jobs = [
  {
    id: "1",
     title: "Project Manager",
    companyImage: "https://via.placeholder.com/150",
    companyName: "Sinotech Limited",
    deadline: "31 Dec 2025",
    summary: {
      vacancy: "02",
      age: "23 to 40 years",
      location: "Dhaka (Banani)",
      salary: "Negotiable",
      experience: "2 to 5 years",
      published: "27 Dec 2025",
    },
    requirements: {
      education: "Bachelor/Honors",
      experience: "2 to 5 years",
      businessAreas: [
        "Chemical Industries",
        "Cement Industry",
        "Sanitary ware",
        "Real Estate",
        "Medical Equipment",
        "Industrial Machineries (Generator, Diesel Engine etc.)",
        "Tiles/Ceramic",
      ],
      freshers: true,
      additional: "Additional Requirements can be added here.",
    },
    responsibilities: [
      "Manage daily operations",
      "Coordinate with team members",
      "Ensure project deadlines are met",
      "Maintain quality standards",
    ],
    skillsAndExpertise: [
      "Project Management",
      "Team Coordination",
      "Problem Solving",
      "Industry Knowledge",
    ],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Only Male",
      jobLocation: "Dhaka (Banani)",
    },
    companyInfo: {
      name: "Sinotech Limited",
      address: "House 52, Road 13/C, Block-E, Banani, Dhaka-1213",
      business:
        "Sinotech is in business of building & construction materials sourcing organization. Our main concentration is on building façade. We are agent of China No. 1 Brand SILANDE Silicone Sealant, SYP Pilkington Glass, Hardware and we are continuously expanding. We provide total solutions for prestigious commercial & residential projects curtain wall, aluminum window etc. We want to establish Sinotech as one of leading distribution companies in Bangladesh. We are looking for talented professionals with ambition, self-motivated to work in challenging business environment.",
    },
  },
  {
    id: "2",
    title: "Senior Software Engineer",
    companyImage: "https://media.licdn.com/dms/image/v2/D4D0BAQEgIDZF3Kcfog/company-logo_200_200/B4DZkQ0RJnG8AU-/0/1756923762981/ilmifytechagency_logo?e=1768435200&v=beta&t=9D4LPDEYypGRUd15g4Sm-zXlnT2RgW_qoVJfFyl9vBo",
    companyName: "IlmiFyTech Agency",
    deadline: "15 Jan 2026",
    summary: {
      vacancy: "03",
      age: "25 to 35 years",
      location: "Dhaka (Gulshan)",
      salary: "Negotiable",
      experience: "3 to 6 years",
      published: "20 Dec 2025",
    },
    requirements: {
      education: "Bachelor/Masters",
      experience: "3 to 6 years",
      businessAreas: ["IT", "Software Development", "AI/ML Projects"],
      freshers: false,
      additional: "Candidates must have strong problem solving skills.",
    },
    responsibilities: [
      "Develop scalable applications",
      "Coordinate with design & QA teams",
      "Implement best coding practices",
      "Maintain code documentation",
    ],
    skillsAndExpertise: ["React", "Node.js", "Next.js", "REST APIs", "Teamwork"],
    compensationAndBenefits: {
      workplace: "Hybrid",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Gulshan)",
    },
    companyInfo: {
      name: "TechSoft Ltd.",
      address: "House 25, Road 8, Gulshan, Dhaka-1212",
      business:
        "TechSoft Ltd. is a software development company focusing on web and mobile applications. We provide modern IT solutions to clients globally.",
    },
  },
    {
    id: "3",
    title: "Marketing Manager",
    companyImage: "https://via.placeholder.com/150",
    companyName: "Bright Marketing Ltd.",
    deadline: "20 Jan 2026",
    summary: {
      vacancy: "01",
      age: "25 to 40 years",
      location: "Dhaka (Dhanmondi)",
      salary: "Negotiable",
      experience: "4 to 7 years",
      published: "28 Dec 2025",
    },
    requirements: {
      education: "Bachelor/MBA",
      experience: "4 to 7 years",
      businessAreas: ["Marketing", "Branding", "Advertising"],
      freshers: false,
      additional: "Strong communication and leadership skills required.",
    },
    responsibilities: [
      "Develop marketing strategies",
      "Manage campaigns",
      "Analyze market trends",
      "Coordinate with sales team",
    ],
    skillsAndExpertise: ["Digital Marketing", "SEO", "Brand Management"],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Dhanmondi)",
    },
    companyInfo: {
      name: "Bright Marketing Ltd.",
      address: "Dhanmondi, Dhaka",
      business: "Marketing and advertising solutions provider.",
    },
  },

  {
    id: "4",
    title: "UI/UX Designer",
    companyImage: "https://via.placeholder.com/150",
    companyName: "DesignPro Studio",
    deadline: "22 Jan 2026",
    summary: {
      vacancy: "02",
      age: "22 to 35 years",
      location: "Remote",
      salary: "Negotiable",
      experience: "2 to 4 years",
      published: "28 Dec 2025",
    },
    requirements: {
      education: "Bachelor",
      experience: "2 to 4 years",
      businessAreas: ["UI/UX", "Product Design"],
      freshers: false,
      additional: "Portfolio required.",
    },
    responsibilities: [
      "Design user interfaces",
      "Create wireframes",
      "Conduct user research",
    ],
    skillsAndExpertise: ["Figma", "Adobe XD", "User Research"],
    compensationAndBenefits: {
      workplace: "Remote",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Remote",
    },
    companyInfo: {
      name: "DesignPro Studio",
      address: "Dhaka, Bangladesh",
      business: "Creative design agency.",
    },
  },

  {
    id: "5",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    deadline: "25 Jan 2026",
    summary: {
      vacancy: "01",
      age: "23 to 35 years",
      location: "Dhaka (Uttara)",
      salary: "Negotiable",
      experience: "1 to 3 years",
      published: "29 Dec 2025",
    },
    requirements: {
      education: "Bachelor/MBA",
      experience: "1 to 3 years",
      businessAreas: ["HR", "Administration"],
      freshers: false,
      additional: "Good interpersonal skills.",
    },
    responsibilities: [
      "Recruitment process",
      "Maintain employee records",
      "Support HR policies",
    ],
    skillsAndExpertise: ["Recruitment", "Communication", "MS Office"],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Uttara)",
    },
    companyInfo: {
      name: "PeopleFirst Ltd.",
      address: "Uttara, Dhaka",
      business: "HR consultancy and staffing services.",
    },
  },
  {
    id: "6",
     title: "Project Manager",
    companyImage: "https://via.placeholder.com/150",
    companyName: "Sinotech Limited",
    deadline: "31 Dec 2025",
    summary: {
      vacancy: "02",
      age: "23 to 40 years",
      location: "Dhaka (Banani)",
      salary: "Negotiable",
      experience: "2 to 5 years",
      published: "27 Dec 2025",
    },
    requirements: {
      education: "Bachelor/Honors",
      experience: "2 to 5 years",
      businessAreas: [
        "Chemical Industries",
        "Cement Industry",
        "Sanitary ware",
        "Real Estate",
        "Medical Equipment",
        "Industrial Machineries (Generator, Diesel Engine etc.)",
        "Tiles/Ceramic",
      ],
      freshers: true,
      additional: "Additional Requirements can be added here.",
    },
    responsibilities: [
      "Manage daily operations",
      "Coordinate with team members",
      "Ensure project deadlines are met",
      "Maintain quality standards",
    ],
    skillsAndExpertise: [
      "Project Management",
      "Team Coordination",
      "Problem Solving",
      "Industry Knowledge",
    ],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Only Male",
      jobLocation: "Dhaka (Banani)",
    },
    companyInfo: {
      name: "Sinotech Limited",
      address: "House 52, Road 13/C, Block-E, Banani, Dhaka-1213",
      business:
        "Sinotech is in business of building & construction materials sourcing organization. Our main concentration is on building façade. We are agent of China No. 1 Brand SILANDE Silicone Sealant, SYP Pilkington Glass, Hardware and we are continuously expanding. We provide total solutions for prestigious commercial & residential projects curtain wall, aluminum window etc. We want to establish Sinotech as one of leading distribution companies in Bangladesh. We are looking for talented professionals with ambition, self-motivated to work in challenging business environment.",
    },
  },
  {
    id: "7",
    title: "Senior Software Engineer",
    companyImage: "https://media.licdn.com/dms/image/v2/D4D0BAQEgIDZF3Kcfog/company-logo_200_200/B4DZkQ0RJnG8AU-/0/1756923762981/ilmifytechagency_logo?e=1768435200&v=beta&t=9D4LPDEYypGRUd15g4Sm-zXlnT2RgW_qoVJfFyl9vBo",
    companyName: "IlmiFyTech Agency",
    deadline: "15 Jan 2026",
    summary: {
      vacancy: "03",
      age: "25 to 35 years",
      location: "Dhaka (Gulshan)",
      salary: "Negotiable",
      experience: "3 to 6 years",
      published: "20 Dec 2025",
    },
    requirements: {
      education: "Bachelor/Masters",
      experience: "3 to 6 years",
      businessAreas: ["IT", "Software Development", "AI/ML Projects"],
      freshers: false,
      additional: "Candidates must have strong problem solving skills.",
    },
    responsibilities: [
      "Develop scalable applications",
      "Coordinate with design & QA teams",
      "Implement best coding practices",
      "Maintain code documentation",
    ],
    skillsAndExpertise: ["React", "Node.js", "Next.js", "REST APIs", "Teamwork"],
    compensationAndBenefits: {
      workplace: "Hybrid",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Gulshan)",
    },
    companyInfo: {
      name: "TechSoft Ltd.",
      address: "House 25, Road 8, Gulshan, Dhaka-1212",
      business:
        "TechSoft Ltd. is a software development company focusing on web and mobile applications. We provide modern IT solutions to clients globally.",
    },
  },
    {
    id: "8",
    title: "Marketing Manager",
    companyImage: "https://via.placeholder.com/150",
    companyName: "Bright Marketing Ltd.",
    deadline: "20 Jan 2026",
    summary: {
      vacancy: "01",
      age: "25 to 40 years",
      location: "Dhaka (Dhanmondi)",
      salary: "Negotiable",
      experience: "4 to 7 years",
      published: "28 Dec 2025",
    },
    requirements: {
      education: "Bachelor/MBA",
      experience: "4 to 7 years",
      businessAreas: ["Marketing", "Branding", "Advertising"],
      freshers: false,
      additional: "Strong communication and leadership skills required.",
    },
    responsibilities: [
      "Develop marketing strategies",
      "Manage campaigns",
      "Analyze market trends",
      "Coordinate with sales team",
    ],
    skillsAndExpertise: ["Digital Marketing", "SEO", "Brand Management"],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Dhanmondi)",
    },
    companyInfo: {
      name: "Bright Marketing Ltd.",
      address: "Dhanmondi, Dhaka",
      business: "Marketing and advertising solutions provider.",
    },
  },

  {
    id: "9",
    title: "UI/UX Designer",
    companyImage: "https://via.placeholder.com/150",
    companyName: "DesignPro Studio",
    deadline: "22 Jan 2026",
    summary: {
      vacancy: "02",
      age: "22 to 35 years",
      location: "Remote",
      salary: "Negotiable",
      experience: "2 to 4 years",
      published: "28 Dec 2025",
    },
    requirements: {
      education: "Bachelor",
      experience: "2 to 4 years",
      businessAreas: ["UI/UX", "Product Design"],
      freshers: false,
      additional: "Portfolio required.",
    },
    responsibilities: [
      "Design user interfaces",
      "Create wireframes",
      "Conduct user research",
    ],
    skillsAndExpertise: ["Figma", "Adobe XD", "User Research"],
    compensationAndBenefits: {
      workplace: "Remote",
      employmentStatus: "Part Time",
      gender: "Any",
      jobLocation: "Remote",
    },
    companyInfo: {
      name: "DesignPro Studio",
      address: "Dhaka, Bangladesh",
      business: "Creative design agency.",
    },
  },

  {
    id: "10",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    deadline: "25 Jan 2026",
    summary: {
      vacancy: "01",
      age: "23 to 35 years",
      location: "Dhaka (Uttara)",
      salary: "Negotiable",
      experience: "1 to 3 years",
      published: "29 Dec 2025",
    },
    requirements: {
      education: "Bachelor/MBA",
      experience: "1 to 3 years",
      businessAreas: ["HR", "Administration"],
      freshers: false,
      additional: "Good interpersonal skills.",
    },
    responsibilities: [
      "Recruitment process",
      "Maintain employee records",
      "Support HR policies",
    ],
    skillsAndExpertise: ["Recruitment", "Communication", "MS Office"],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Uttara)",
    },
    companyInfo: {
      name: "PeopleFirst Ltd.",
      address: "Uttara, Dhaka",
      business: "HR consultancy and staffing services.",
    },
  },
  {
    id: "11",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    deadline: "25 Jan 2026",
    summary: {
      vacancy: "01",
      age: "23 to 35 years",
      location: "Dhaka (Uttara)",
      salary: "Negotiable",
      experience: "1 to 3 years",
      published: "29 Dec 2025",
    },
    requirements: {
      education: "Bachelor/MBA",
      experience: "1 to 3 years",
      businessAreas: ["HR", "Administration"],
      freshers: false,
      additional: "Good interpersonal skills.",
    },
    responsibilities: [
      "Recruitment process",
      "Maintain employee records",
      "Support HR policies",
    ],
    skillsAndExpertise: ["Recruitment", "Communication", "MS Office"],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Uttara)",
    },
    companyInfo: {
      name: "PeopleFirst Ltd.",
      address: "Uttara, Dhaka",
      business: "HR consultancy and staffing services.",
    },
  },
  {
    id: "12",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    deadline: "25 Jan 2026",
    summary: {
      vacancy: "01",
      age: "23 to 35 years",
      location: "Dhaka (Uttara)",
      salary: "Negotiable",
      experience: "1 to 3 years",
      published: "29 Dec 2025",
    },
    requirements: {
      education: "Bachelor/MBA",
      experience: "1 to 3 years",
      businessAreas: ["HR", "Administration"],
      freshers: false,
      additional: "Good interpersonal skills.",
    },
    responsibilities: [
      "Recruitment process",
      "Maintain employee records",
      "Support HR policies",
    ],
    skillsAndExpertise: ["Recruitment", "Communication", "MS Office"],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Uttara)",
    },
    companyInfo: {
      name: "PeopleFirst Ltd.",
      address: "Uttara, Dhaka",
      business: "HR consultancy and staffing services.",
    },
  },
  {
    id: "13",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    deadline: "25 Jan 2026",
    summary: {
      vacancy: "01",
      age: "23 to 35 years",
      location: "Dhaka (Uttara)",
      salary: "Negotiable",
      experience: "1 to 3 years",
      published: "29 Dec 2025",
    },
    requirements: {
      education: "Bachelor/MBA",
      experience: "1 to 3 years",
      businessAreas: ["HR", "Administration"],
      freshers: false,
      additional: "Good interpersonal skills.",
    },
    responsibilities: [
      "Recruitment process",
      "Maintain employee records",
      "Support HR policies",
    ],
    skillsAndExpertise: ["Recruitment", "Communication", "MS Office"],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Uttara)",
    },
    companyInfo: {
      name: "PeopleFirst Ltd.",
      address: "Uttara, Dhaka",
      business: "HR consultancy and staffing services.",
    },
  },
  {
    id: "14",
    title: "HR Executive",
    companyImage: "https://via.placeholder.com/150",
    companyName: "PeopleFirst Ltd.",
    deadline: "25 Jan 2026",
    summary: {
      vacancy: "01",
      age: "23 to 35 years",
      location: "Dhaka (Uttara)",
      salary: "Negotiable",
      experience: "1 to 3 years",
      published: "29 Dec 2025",
    },
    requirements: {
      education: "Bachelor/MBA",
      experience: "1 to 3 years",
      businessAreas: ["HR", "Administration"],
      freshers: false,
      additional: "Good interpersonal skills.",
    },
    responsibilities: [
      "Recruitment process",
      "Maintain employee records",
      "Support HR policies",
    ],
    skillsAndExpertise: ["Recruitment", "Communication", "MS Office"],
    compensationAndBenefits: {
      workplace: "Work at office",
      employmentStatus: "Full Time",
      gender: "Any",
      jobLocation: "Dhaka (Uttara)",
    },
    companyInfo: {
      name: "PeopleFirst Ltd.",
      address: "Uttara, Dhaka",
      business: "HR consultancy and staffing services.",
    },
  },

 
];

const JobData = () => {
  return (
    <div>
      
    </div>
  );
};

export default JobData;