const majorServiceData = [
  {
    id: 1,
    slug: "cms-services",
    category: "WordPress",
    title: "WordPress CMS Services",
    description: `At iLMiFY, we provide professional WordPress CMS services to help businesses manage content efficiently.
    From custom theme development to performance optimization, we build scalable, secure, and user-friendly WordPress solutions.`,
    image: "/assets/images/wordpress.avif",
    features: [
      "Custom WordPress Website Design",
      "WordPress Theme Customization",
      "WordPress Plugin Development",
      "WordPress Security Optimization",
      "WordPress SEO Optimization",
      "WordPress Website Maintenance",
      "WooCommerce Development",
      "WordPress Migration Services",
      "Performance Optimization",
      "Custom Forms & Functionality",
      "WordPress API Integration",
      "Backup & Restore Solutions",
      "Responsive WordPress Design",
      "Custom Post Types",
      "WordPress Multisite Management",
    ],

  
  },

  {
    id: 2,
    slug: "cms-services",
    category: "Shopify",
    title: "Shopify CMS Services",
    description: `We deliver powerful Shopify CMS solutions that help businesses build, manage, and scale high-performing online stores.
    Our Shopify services focus on design, conversion optimization, and seamless integrations.`,
    image: "/assets/images/shopify.avif",
    features: [
      "Custom Shopify Store Design",
      "Shopify Theme Customization",
      "Shopify App Development",
      "Shopify SEO Optimization",
      "Performance Optimization",
      "Shopify Maintenance & Support",
      "Payment Gateway Integration",
      "Inventory Management Setup",
      "Custom Product Pages",
      "Analytics & Tracking Setup",
      "Marketing Integrations",
      "Checkout Optimization",
      "Shopify Migration Services",
      "Mobile Optimization",
      "Multi-language Store Setup",
    ],


  },

  {
    id: 3,
    slug: "cms-services",
    category: "Wix",
    title: "Wix CMS Services",
    description: `Our Wix CMS services help businesses create visually stunning and easy-to-manage websites.
    We focus on custom design, performance optimization, and business-driven functionality using Wix.`,
    image: "/assets/images/wix.avif",
    features: [
      "Custom Wix Website Design",
      "Wix Editor & Editor X Customization",
      "Wix CMS Collections Setup",
      "Wix SEO Optimization",
      "Wix Performance Optimization",
      "Wix Website Maintenance",
      "Custom Wix Forms & Automations",
      "Wix Booking & Appointment Setup",
      "Wix E-commerce Solutions",
      "Wix Payment Integration",
      "Wix Animations & Interactions",
      "Mobile Responsive Design",
      "Custom Wix Landing Pages",
      "Wix Blog Setup",
      "Third-Party App Integrations",
    ],


  },

  {
    id: 4,
    slug: "cms-services",
    category: "Squarespace",
    title: "Squarespace CMS Services",
    description: `We offer professional Squarespace CMS solutions for businesses seeking elegant, high-quality websites.
    Our services focus on design excellence, content management, and smooth user experience.`,
    image: "/assets/images/squrespace.avif",
    features: [
      "Custom Squarespace Website Design",
      "Squarespace Template Customization",
      "Squarespace CMS Setup",
      "SEO Optimization",
      "Squarespace Performance Optimization",
      "Website Maintenance & Support",
      "E-commerce Setup",
      "Payment Gateway Integration",
      "Custom Content Layouts",
      "Squarespace Blogging Setup",
      "Analytics Integration",
      "Mobile Responsive Design",
      "Custom Landing Pages",
      "Domain & Hosting Setup",
      "Third-Party Integrations",
    ],


  },
  {
    id: 5,
    slug: "custom-development",
    category: "Frontend",
    title: "Frontend Development Services",
    description: `At iLMiFY, we build modern, fast, and responsive frontend applications using the latest technologies.
    Our focus is on clean UI, smooth UX, and high performance across all devices.`,
    image: "/assets/images/frontend.avif",
    features: [
      "React.js Application Development",
      "Next.js Website & App Development",
      "Vue.js & Vite Projects",
      "Tailwind CSS & Bootstrap UI",
      "Responsive & Mobile-First Design",
      "Single Page Applications (SPA)",
      "UI/UX Implementation from Figma",
      "Component-Based Architecture",
      "SEO-Friendly Frontend",
      "Performance Optimization",
      "Animation with Framer Motion",
      "Cross-Browser Compatibility",
      "Reusable UI Components",
      "Progressive Web Apps (PWA)",
      "Frontend Code Refactoring",
    ],


  },
  {
    id: 6,
    slug: "custom-development",
    category: "Backend",
    title: "Backend Development Services",
    description: `We develop secure, scalable, and high-performance backend systems that power modern web applications.
    Our backend solutions ensure smooth data handling and reliable APIs.`,
    image: "/assets/images/backend.jpg",
    features: [
      "Node.js & Express.js Development",
      "Laravel Backend Development",
      "RESTful API Development",
      "GraphQL API Integration",
      "Custom Business Logic",
      "Server-Side Validation",
      "Role-Based Access Control",
      "Third-Party API Integration",
      "Payment Gateway Integration",
      "Microservices Architecture",
      "Backend Performance Optimization",
      "Secure Data Handling",
      "Cron Jobs & Background Tasks",
      "Error Handling & Logging",
      "Scalable Server Architecture",
    ],


  },
  {
    id: 7,
    slug: "custom-development",
    category: "Databases",
    title: "Database Design & Management",
    description: `We design and manage efficient, secure, and scalable databases to ensure data integrity and performance.
    Our solutions support both relational and non-relational data models.`,
    image: "/assets/images/database.jpg",
    features: [
      "MongoDB Database Design",
      "MySQL & PostgreSQL Development",
      "Database Schema Design",
      "Data Modeling & Optimization",
      "Indexing & Query Optimization",
      "Database Migration Services",
      "Cloud Database Setup",
      "Backup & Recovery Solutions",
      "Data Security & Encryption",
      "High Availability Configuration",
      "Database Performance Tuning",
      "NoSQL & SQL Integration",
      "Data Validation Rules",
      "Large Data Handling",
      "Scalable Database Architecture",
    ],


  },
  {
    id: 8,
    slug: "custom-development",
    category: "Authentication",
    title: "Authentication & Security Services",
    description: `We implement secure authentication and authorization systems to protect user data and applications.
    Our solutions follow industry best practices and modern security standards.`,
    image: "/assets/images/authentication.avif",
    features: [
      "JWT Authentication",
      "Firebase Authentication",
      "OAuth (Google, GitHub, Facebook)",
      "Email & Password Login System",
      "Social Login Integration",
      "Role-Based Authorization",
      "Protected Routes Implementation",
      "Two-Factor Authentication (2FA)",
      "Session Management",
      "Password Hashing & Encryption",
      "Secure API Authentication",
      "Admin & User Access Control",
      "Token Refresh Strategy",
      "Login Activity Monitoring",
      "Security Best Practices Implementation",
    ],


  },
  {
    id: 9,
    slug: "digital-marketing",
    category: "Social Media Marketing",
    title: "Social Media Marketing Services",
    description: `At iLMiFY, we help brands grow and engage their audience through powerful social media marketing strategies.
    From content creation to paid campaigns, we manage your social presence to increase reach, engagement, and conversions.`,
    image: "/assets/images/social-media-markeking.avif",
    features: [
      "Social Media Strategy Planning",
      "Facebook & Instagram Marketing",
      "LinkedIn & Twitter Marketing",
      "Content Creation & Scheduling",
      "Paid Social Media Advertising",
      "Audience Targeting & Growth",
      "Brand Awareness Campaigns",
      "Social Media Account Management",
      "Performance Analytics & Reporting",
      "Hashtag & Trend Research",
      "Community Management",
      "Influencer Collaboration",
      "Conversion Tracking",
      "Creative Ad Design",
      "Monthly Performance Reports",
    ],

  },
  {
    id: 10,
    slug: "digital-marketing",
    category: "Search Engine Optimization",
    title: "SEO Services",
    description: `At iLMiFY, we provide data-driven SEO services to improve your website’s visibility on search engines.
    Our proven strategies help increase organic traffic, rankings, and long-term online growth.`,
    image: "/assets/images/seo.avif",
    features: [
      "Keyword Research & Analysis",
      "On-Page SEO Optimization",
      "Technical SEO Audit",
      "Website Speed Optimization",
      "Mobile SEO Optimization",
      "Content SEO Strategy",
      "Meta Tags & Schema Markup",
      "Internal Linking Optimization",
      "Local SEO Services",
      "Google Search Console Setup",
      "SEO-Friendly URL Structure",
      "Competitor SEO Analysis",
      "Backlink Strategy",
      "Monthly SEO Reports",
      "Long-Term Ranking Growth",
    ],


  },
  {
    id: 11,
    slug: "digital-marketing",
    category: "Search Engine Marketing",
    title: "Search Engine Marketing (SEM) Services",
    description: `At iLMiFY, we run high-converting search engine marketing campaigns to bring instant traffic and qualified leads.
    Our SEM strategies maximize ROI through smart bidding, targeting, and ad optimization.`,
    image: "/assets/images/search-engine marketing.avif",
    features: [
      "Google Ads Campaign Setup",
      "Keyword & Bid Strategy",
      "Search & Display Ads",
      "Remarketing Campaigns",
      "Ad Copywriting",
      "Landing Page Optimization",
      "Conversion Tracking Setup",
      "A/B Testing Ads",
      "Budget & Cost Optimization",
      "Performance Monitoring",
      "Click Fraud Prevention",
      "Audience Targeting",
      "Campaign Scaling",
      "ROI-Focused Strategy",
      "Detailed Ad Reports",
    ],

  },
  {
    id: 12,
    slug: "digital-marketing",
    category: "Content Marketing",
    title: "Content Marketing Services",
    description: `At iLMiFY, we create valuable and engaging content that attracts, educates, and converts your audience.
    Our content marketing strategies strengthen your brand authority and drive sustainable growth.`,
    image: "/assets/images/content-marketing.jpg",
    features: [
      "Content Strategy Planning",
      "Blog Writing & Publishing",
      "SEO-Optimized Content",
      "Website Content Writing",
      "Social Media Content Creation",
      "Copywriting for Ads",
      "Email Marketing Content",
      "Landing Page Content",
      "Content Calendar Management",
      "Audience-Focused Storytelling",
      "Brand Voice Development",
      "Content Performance Analysis",
      "Lead Magnet Creation",
      "Content Distribution Strategy",
      "Long-Term Content Growth",
    ],


  },
  {
    id: 13,
    slug: "graphics-design",
    category: "Creative Design",
    title: "Graphics Design Services",
    description: `At iLMiFY, we offer creative graphic design services that help businesses communicate visually and stand out.
    Our designs are modern, impactful, and aligned with your brand goals.`,
    image: "/assets/images/creative-design.avif",
    features: [
      "Creative Visual Design",
      "Custom Graphic Concepts",
      "Modern & Clean Layouts",
      "Brand-Focused Design",
      "High-Resolution Designs",
      "Print & Digital Graphics",
      "Color & Typography Selection",
      "Unlimited Revisions",
      "Fast Turnaround Time",
    ],

 
  },
  {
    id: 14,
    slug: "graphics-design",
    category: "Ad Creatives",
    title: "Ad Creative Design",
    description: `We design high-converting ad creatives that capture attention and drive results across digital platforms.
    Our ad designs are optimized for engagement and performance.`,
    image: "/assets/images/ad-creatives.avif",
    features: [
      "Facebook & Instagram Ads",
      "Google Display Ads",
      "YouTube Thumbnail Ads",
      "Promotional Banner Design",
      "Call-to-Action Focused Design",
      "A/B Test Ready Creatives",
      "Platform-Specific Sizes",
      "Eye-Catching Visuals",
    ],


  },
  {
    id: 15,
    slug: "graphics-design",
    category: "Brand Identity Design",
    title: "Brand Identity Design",
    description: `We build strong and consistent brand identities that reflect your business values and vision.
    From logos to brand guidelines, we ensure your brand stands out everywhere.`,
    image: "/assets/images/brand-identity.avif",
    features: [
      "Logo Design",
      "Brand Color Palette",
      "Typography Selection",
      "Brand Guidelines",
      "Business Card Design",
      "Letterhead Design",
      "Brand Consistency Strategy",
      "Rebranding Solutions",
    ],


  },
  {
    id: 16,
    slug: "graphics-design",
    category: "Social Media Posts & Banners",
    title: "Social Media Design",
    description: `We design engaging social media posts and banners to boost your online presence.
    Our designs are tailored for each platform to maximize reach and engagement.`,
    image: "/assets/images/social-media-banner.jpg",
    features: [
      "Facebook Post Design",
      "Instagram Post & Story Design",
      "LinkedIn Banner Design",
      "YouTube Channel Art",
      "Social Media Ad Banners",
      "Custom Post Templates",
      "Branded Visual Content",
      "Platform-Optimized Sizes",
    ],


  },
  {
    id: 17,
    slug: "app-development",
    category: "Android App",
    title: "Android App Development Services",
    description: `At iLMiFY, we provide high-quality Android app development services tailored to your business needs.
    From concept to deployment, we build secure, scalable, and high-performance Android applications.`,
    image: "/assets/images/android.avif",
    features: [
      "Custom Android App Development",
      "UI/UX Design for Android Apps",
      "Native Android (Kotlin & Java)",
      "Firebase Integration",
      "API Integration",
      "App Performance Optimization",
      "Play Store Deployment",
      "App Security Implementation",
      "Bug Fixing & Maintenance",
      "Third-Party SDK Integration",
      "Offline Functionality",
      "Push Notifications",
      "Android App Testing",
      "App Upgrade & Migration",
      "Ongoing Support & Maintenance",
    ],


  },
  {
    id: 18,
    slug: "app-development",
    category: "IOS App",
    title: "iOS App Development Services",
    description: `At iLMiFY, we build powerful and elegant iOS applications for iPhone and iPad devices.
    Our apps are optimized for performance, security, and seamless user experience.`,
    image: "/assets/images/ios.jpg",
    features: [
      "Custom iOS App Development",
      "UI/UX Design for iOS Apps",
      "Swift & SwiftUI Development",
      "Apple App Store Deployment",
      "API & Backend Integration",
      "Secure Data Storage",
      "Performance Optimization",
      "Push Notifications",
      "Third-Party API Integration",
      "iPad App Development",
      "App Testing & QA",
      "Bug Fixes & Updates",
      "iOS App Maintenance",
      "App Upgrade & Migration",
      "Ongoing Support & Maintenance",
    ],


  },
  {
    id: 19,
    slug: "app-development",
    category: "Web App",
    title: "Web Application Development Services",
    description: `At iLMiFY, we create fast, scalable, and secure web applications for modern businesses.
    Our web apps are built with the latest technologies to ensure performance and reliability.`,
    image: "/assets/images/web-app.jpg",
    features: [
      "Custom Web App Development",
      "React & Next.js Applications",
      "Backend Development (Node, Laravel)",
      "REST & GraphQL API Integration",
      "Authentication & Authorization",
      "Database Design & Management",
      "Performance Optimization",
      "Responsive Web Design",
      "Cloud Deployment",
      "Third-Party Integrations",
      "Security Best Practices",
      "Admin Dashboards",
      "Progressive Web Apps (PWA)",
      "Web App Testing",
      "Maintenance & Support",
    ],


  },
  {
    id: 20,
    slug: "app-development",
    category: "Desktop App",
    title: "Desktop Application Development Services",
    description: `At iLMiFY, we develop robust and secure desktop applications for Windows, macOS, and Linux.
    Our solutions are tailored for performance, usability, and long-term scalability.`,
    image: "/assets/images/desktop-app.avif",
    features: [
      "Custom Desktop App Development",
      "Cross-Platform Applications",
      "Electron & Tauri Apps",
      "Windows, macOS & Linux Support",
      "Offline Functionality",
      "High-Performance Architecture",
      "Secure Data Management",
      "UI/UX Design for Desktop",
      "API & Database Integration",
      "App Packaging & Distribution",
      "Auto Updates",
      "Bug Fixing & Optimization",
      "Legacy App Modernization",
      "Desktop App Testing",
      "Maintenance & Support",
    ],


  },
  {
    id: 21,
    slug: "tracking-analytics",
    category: "Google Tag Manager",
    title: "Google Tag Manager Setup & Management",
    description: `We provide professional Google Tag Manager (GTM) services to help businesses manage tracking scripts efficiently 
    without touching website code. Our GTM solutions ensure accurate data collection, faster deployment, and better marketing insights.`,
    image: "/assets/images/google-tag-manager.avif",
    features: [
      "Google Tag Manager Account Setup",
      "Tag & Trigger Configuration",
      "Conversion Tracking Setup",
      "Custom Event Tracking",
      "GA4 Integration",
      "Facebook & Google Ads Tag Setup",
      "Enhanced Ecommerce Tracking",
      "Debugging & Error Fixing",
      "Consent Mode Implementation",
      "Third-Party Script Management",
      "Data Layer Implementation",
      "Cross-Domain Tracking",
      "Performance Optimization",
      "GTM Version Control",
      "Ongoing GTM Maintenance",
    ],


  },
  {
    id: 22,
    slug: "tracking-analytics",
    category: "Meta Pixel Conversion API",
    title: "Meta Pixel & Conversion API Integration",
    description: `We implement Meta Pixel and Conversion API (CAPI) to ensure accurate event tracking, even with ad blockers 
    and browser privacy restrictions. This helps improve Facebook ad performance and conversion attribution.`,
    image: "/assets/images/meta-pixel.avif",
    features: [
      "Meta Pixel Setup",
      "Conversion API (CAPI) Integration",
      "Server-Side Event Tracking",
      "Purchase & Lead Event Tracking",
      "Facebook Ads Conversion Tracking",
      "iOS 14+ Tracking Compliance",
      "Deduplication Setup",
      "Custom Event Configuration",
      "Shopify & WooCommerce Integration",
      "GTM Server-Side Setup",
      "Event Debugging & Testing",
      "Privacy-Safe Tracking",
      "Improved ROAS Optimization",
      "Advanced Attribution Tracking",
      "Ongoing Monitoring & Support",
    ],


  },
  {
    id: 23,
    slug: "tracking-analytics",
    category: "Google Analytics",
    title: "Google Analytics 4 (GA4)",
    description: `We help businesses set up and optimize Google Analytics 4 to gain deep insights into user behavior, 
    traffic sources, and conversion performance for data-driven decisions.`,
    image: "/assets/images/google-analytics.avif",
    features: [
      "Google Analytics 4 Setup",
      "Universal Analytics Migration",
      "Custom Event Tracking",
      "Conversion & Goal Setup",
      "User Behavior Analysis",
      "Ecommerce Tracking",
      "Cross-Device Tracking",
      "Traffic Source Analysis",
      "Custom Reports & Dashboards",
      "GA4 + GTM Integration",
      "Data Accuracy Optimization",
      "Funnel Analysis",
      "Audience Segmentation",
      "Privacy & Cookie Compliance",
      "Ongoing Analytics Support",
    ],

  
  },
  {
    id: 24,
    slug: "tracking-analytics",
    category: "Server Side Tracking",
    title: "Server-Side Tracking Implementation",
    description: `We implement server-side tracking solutions to improve data accuracy, bypass ad blockers, 
    enhance website performance, and ensure compliance with modern privacy regulations.`,
    image: "/assets/images/server-side-tracking.jpg",
    features: [
      "Server-Side Google Tag Manager Setup",
      "GA4 Server-Side Tracking",
      "Meta Conversion API Server Integration",
      "Improved Data Accuracy",
      "Ad Blocker Bypass Tracking",
      "Cookie & Privacy Compliance",
      "Custom Server Events",
      "Cloud Hosting Configuration",
      "Reduced Page Load Time",
      "First-Party Data Collection",
      "Advanced Conversion Tracking",
      "Cross-Platform Event Sync",
      "Secure Data Handling",
      "Scalable Tracking Architecture",
      "Ongoing Server Maintenance",
    ],

 
  },
];

export default majorServiceData;
