// PricingData.ts

// 1. Define reusable string literals
const SERVICE_CATEGORIES = [
  "WordPress",
  "Shopify",
  "Wix",
  "Squarespace",
  "Frontend",
  "Backend",
  "Databases",
  "Authentication",
  "Social Media Marketing",
  "Search Engine Optimization",
  "Search Engine Marketing",
  "Content Marketing",
  "Creative Design",
  "Ad Creatives",
  "Brand Identity Design",
  "Social Media Posts & Banners",
  "Android App",
  "iOS App",
  "Web App",
  "Desktop App",
  "Google Tag Manager",
  "Meta Pixel Conversion API",
  "Google Analytics",
  "Server Side Tracking",
] as const;

const SERVICE_SLUGS = [
  "wordpress",
  "shopify",
  "wix",
  "squarespace",
  "frontend",
  "backend",
  "databases",
  "authentication",
  "social-media-marketing",
  "search-engine-optimization",
  "search-engine-marketing",
  "content-marketing",
  "creative-design",
  "ad-creatives",
  "brand-identity-design",
  "social-media-design",
  "android-app",
  "ios-app",
  "web-app",
  "desktop-app",
  "google-tag-manager",
  "meta-pixel-conversion-api",
  "google-analytics",
  "server-side-tracking",
] as const;

// 2. Define types
type ServiceCategory = typeof SERVICE_CATEGORIES[number];
type ServiceSlug = typeof SERVICE_SLUGS[number];

interface PricingPackage {
  name: string;
  price: string;
  deliveryTime: string;
  revisions: string;
  features: string[];
}

interface PricingItem {
  id: number;
  slug: string;
  serviceSlug: ServiceSlug;
  category: ServiceCategory;
  title: string;
  pricing: {
    basic: PricingPackage;
    standard: PricingPackage;
    premium: PricingPackage;
  };
}
export  const PricingData: PricingItem[] = [
  {
    id: 1,
    slug: "cms-services",
    serviceSlug: "wordpress",
    category: "WordPress",
    title: "WordPress",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "5 Days",
        revisions: "2 Revisions",
        features: [
          "CMS Installation & Setup",
          "Pre-made Theme Setup",
          "Up to 5 Pages",
          "Responsive Design",
          "Basic SEO Setup",
          "Contact Form Setup",
          "Essential Plugin Installation",
          "Basic Security Configuration",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "7 Days",
        revisions: "4 Revisions",
        features: [
          "Custom CMS Design",
          "Up to 10 Pages",
          "Theme Customization",
          "SEO Optimization",
          "Speed Optimization",
          "Security Setup",
          "Analytics Integration",
          "Performance Cache Setup",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "10 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Fully Custom CMS Website",
          "Unlimited Pages",
          "Advanced SEO",
          "Performance Optimization",
          "Security Hardening",
          "E-commerce Integration",
          "Post-Launch Support",
          "Custom Feature Development",
        ],
      },
    },
  },

  {
    id: 2,
    slug: "cms-services",
    serviceSlug: "shopify",
    category: "Shopify",
    title: "Shopify",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "7 Days",
        revisions: "2 Revisions",
        features: [
          "Shopify Store Setup",
          "Pre-made Theme Configuration",
          "Up to 10 Products",
          "Responsive Store Design",
          "Basic App Installation",
          "Payment Gateway Setup",
          "Contact & Policy Pages",
          "Basic SEO Configuration",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "10 Days",
        revisions: "4 Revisions",
        features: [
          "Custom Theme Customization",
          "Up to 30 Products",
          "Product & Collection Setup",
          "Advanced App Integration",
          "Payment & Shipping Configuration",
          "On-page SEO Optimization",
          "Performance Optimization",
          "Analytics & Tracking Setup",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "14 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Fully Custom Shopify Store",
          "Unlimited Products",
          "Custom Sections & Features",
          "Advanced App & API Integration",
          "Multi-currency & Multi-language",
          "Conversion Optimization",
          "Security & Store Hardening",
          "Post-Launch Support",
        ],
      },
    },
  },

  {
    id: 3,
    slug: "cms-services",
    serviceSlug: "wix",
    category: "Wix",
    title: "Wix",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "5 Days",
        revisions: "2 Revisions",
        features: [
          "Wix Website Setup",
          "Template Selection & Setup",
          "Up to 5 Pages",
          "Responsive Design",
          "Basic SEO Setup",
          "Contact Form Integration",
          "Basic App Installation",
          "Website Publishing",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "7 Days",
        revisions: "4 Revisions",
        features: [
          "Custom Wix Design",
          "Up to 10 Pages",
          "Advanced SEO Optimization",
          "Wix App Market Integration",
          "Blog Setup",
          "Speed Optimization",
          "Analytics Integration",
          "Custom Forms & Sections",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "10 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Fully Custom Wix Website",
          "Unlimited Pages",
          "Advanced Design Customization",
          "E-commerce Setup",
          "Advanced SEO & Performance",
          "Security & Backup Setup",
          "CRM & Automation Setup",
          "Post-Launch Support",
        ],
      },
    },
  },

  {
    id: 4,
    slug: "cms-services",
    serviceSlug: "squarespace",
    category: "Squarespace",
    title: "Squarespace",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Squarespace Website Setup",
          "Template Selection & Setup",
          "Up to 5 Pages",
          "Responsive Design",
          "Basic SEO Setup",
          "Contact Form Integration",
          "Image & Content Placement",
          "Website Publishing",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "Custom Squarespace Design",
          "Up to 10 Pages",
          "Advanced SEO Optimization",
          "Blog Setup",
          "Custom Sections & Layouts",
          "Speed Optimization",
          "Analytics Integration",
          "Form & Newsletter Setup",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Fully Custom Squarespace Website",
          "Unlimited Pages",
          "Advanced Design Customization",
          "E-commerce Setup",
          "Advanced SEO & Performance",
          "Security & Backup Setup",
          "CRM & Automation Integration",
          "Post-Launch Support",
        ],
      },
    },
  },

  {
    id: 5,
    slug: "custom-development",
    serviceSlug: "frontend",
    category: "Frontend",
    title: "Frontend",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "10 Days",
        revisions: "2 Revisions",
        features: [
          "Basic UI Design",
          "Responsive Layout",
          "HTML, CSS & JavaScript",
          "API Integration",
          "Authentication Setup",
          "Cross-Browser Compatibility",
          "Basic Performance Optimization",
          "Code Deployment Support",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "15 Days",
        revisions: "4 Revisions",
        features: [
          "Custom Frontend Development",
          "React / Next.js Implementation",
          "Backend API Integration",
          "State Management",
          "Form Validation & Error Handling",
          "Performance Optimization",
          "SEO-Friendly Structure",
          "Testing & Bug Fixing",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "21 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Enterprise-Level Frontend",
          "Advanced UI/UX Animations",
          "Scalable Component Architecture",
          "Advanced State Management",
          "Security Best Practices",
          "Accessibility (WCAG) Compliance",
          "CI/CD Deployment Support",
          "Post-Launch Maintenance",
        ],
      },
    },
  },
  {
    id: 6,
    slug: "custom-development",
    serviceSlug: "backend",
    category: "Backend",
    title: "Backend",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Backend Project Setup",
          "REST API Development",
          "Database Schema Design",
          "Basic CRUD Operations",
          "Authentication & Authorization",
          "Environment Configuration",
          "Basic Error Handling",
          "Deployment Assistance",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "Advanced REST API Development",
          "JWT Authentication",
          "Database Optimization",
          "Role-Based Access Control",
          "Third-Party API Integration",
          "Validation & Error Management",
          "Performance Optimization",
          "Testing & Debugging",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Scalable Backend Architecture",
          "Microservices / Modular Design",
          "Advanced Security Practices",
          "Server-Side Caching",
          "Real-Time Features (WebSockets)",
          "Advanced Logging & Monitoring",
          "CI/CD Pipeline Setup",
          "Post-Launch Support",
        ],
      },
    },
  },
  {
    id: 7,
    slug: "custom-development",
    serviceSlug: "databases",
    category: "Databases",
    title: "Databases",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Database Setup & Configuration",
          "Schema & Table Design",
          "Basic CRUD Operations",
          "Primary & Foreign Keys Setup",
          "Indexing for Performance",
          "Basic Data Validation",
          "Backup Configuration",
          "Local / Cloud Deployment",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "Advanced Schema Design",
          "Relational & NoSQL Modeling",
          "Query Optimization",
          "Stored Procedures / Aggregations",
          "Database Security Rules",
          "Automated Backups",
          "Data Migration Support",
          "Performance Monitoring",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Scalable Database Architecture",
          "High Availability & Replication",
          "Advanced Indexing Strategies",
          "Sharding / Partitioning",
          "Encryption at Rest & Transit",
          "Disaster Recovery Setup",
          "Advanced Monitoring & Alerts",
          "Post-Launch Optimization Support",
        ],
      },
    },
  },
  {
    id: 8,
    slug: "custom-development",
    serviceSlug: "authentication",
    category: "Authentication",
    title: "Authentication",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Authentication System Setup",
          "Email & Password Login",
          "User Registration Flow",
          "Password Hashing & Security",
          "Login / Logout Functionality",
          "Basic Role Setup",
          "Session Management",
          "Basic Error Handling",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "JWT-Based Authentication",
          "Role-Based Access Control",
          "Protected Routes / APIs",
          "Password Reset & Email Verification",
          "OAuth (Google / GitHub) Login",
          "Token Refresh Strategy",
          "Security Best Practices",
          "Testing & Debugging",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Advanced Authentication Architecture",
          "Multi-Factor Authentication (MFA)",
          "Single Sign-On (SSO)",
          "Third-Party Identity Provider Integration",
          "Advanced Session & Token Management",
          "Rate Limiting & Brute-Force Protection",
          "Security Audit & Hardening",
          "Post-Launch Support",
        ],
      },
    },
  },
  {
    id: 9,
    slug: "digital-marketing",
    serviceSlug: "social-media-marketing",
    category: "Social Media Marketing",
    title: "Social Media Marketing",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Google Analytics Setup",
          "Basic Event Tracking",
          "Social Media Account Setup",
          "Content Calendar Creation",
          "Basic Post Design",
          "Scheduling Posts",
          "Audience Engagement Monitoring",
          "Basic Campaign Reporting",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Content Strategy & Planning",
          "Creative Post Design",
          "Ad Campaign Setup",
          "Performance Analytics",
          "Community Engagement Management",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Advanced Analytics & Reporting",
          "Meta CAPI Integration",
          "Multi-Platform Campaign Management",
          "Paid Ads Optimization",
          "Influencer Collaboration Setup",
          "Social Listening & Monitoring",
          "Advanced Content Strategy",
          "Post-Launch Support & Consulting",
        ],
      },
    },
  },
  {
    id: 10,
    slug: "digital-marketing",
    serviceSlug: "search-engine-optimization",
    category: "Search Engine Optimization",
    title: "Search Engine Optimization",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Google Analytics Setup",
          "Basic Event Tracking",
          "Keyword Research",
          "On-Page SEO Optimization",
          "Meta Tags Setup",
          "URL Structure Optimization",
          "Basic Content Recommendations",
          "Google Search Console Setup",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced Keyword Research",
          "Competitor Analysis",
          "Content Optimization Strategy",
          "Internal Linking Improvements",
          "Technical SEO Fixes",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full SEO Audit & Recommendations",
          "Backlink Strategy & Setup",
          "Schema Markup Implementation",
          "Continuous SEO Monitoring & Support",
        ],
      },
    },
  },
  {
    id: 11,
    slug: "digital-marketing",
    serviceSlug: "search-engine-marketing",
    category: "Search Engine Marketing",
    title: "Search Engine Marketing",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Google Analytics Setup",
          "Basic Event Tracking",
          "Campaign Setup",
          "Keyword Selection",
          "Ad Copywriting",
          "Basic Bid Management",
          "Landing Page Optimization",
          "Performance Monitoring",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced Keyword Research",
          "Competitor Ad Analysis",
          "Bid & Budget Optimization",
          "A/B Ad Testing",
          "Reporting & Recommendations",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full Campaign Strategy",
          "Conversion Rate Optimization",
          "Remarketing Setup",
          "Ongoing Campaign Management",
        ],
      },
    },
  },
  {
    id: 12,
    slug: "digital-marketing",
    serviceSlug: "content-marketing",
    category: "Content Marketing",
    title: "Content Marketing",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Google Analytics Setup",
          "Basic Event Tracking",
          "Content Audit",
          "Blog Post Creation",
          "Social Media Content",
          "Basic SEO Optimization",
          "Content Calendar Setup",
          "Performance Monitoring",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced Content Strategy",
          "Competitor Analysis",
          "SEO-Friendly Copywriting",
          "Content Promotion Strategy",
          "Performance Reporting",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full Content Marketing Plan",
          "Multichannel Content Distribution",
          "Conversion Optimization",
          "Ongoing Content Management",
        ],
      },
    },
  },
  {
    id: 13,
    slug: "graphics-design",
    serviceSlug: "creative-design",
    category: "Creative Design",
    title: "Creative Design",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Logo Concept Design",
          "Color Palette Selection",
          "Typography Guidance",
          "Brand Style Suggestions",
          "Basic Graphic Templates",
          "Social Media Banner Setup",
          "Google Analytics Setup",
          "Basic Event Tracking",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced Logo & Branding",
          "Marketing Materials Design",
          "Social Media Graphics",
          "Business Card & Letterhead Design",
          "Performance Review & Recommendations",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Complete Brand Identity",
          "Multi-Platform Marketing Assets",
          "Packaging & Product Design",
          "Ongoing Creative Support",
        ],
      },
    },
  },
  {
    id: 14,
    slug: "graphics-design",
    serviceSlug: "ad-creatives",
    category: "Ad Creatives",
    title: "Ad Creatives",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Banner Design Concept",
          "Social Media Ad Template",
          "Facebook Ad Creatives",
          "Instagram Ad Creatives",
          "Basic Motion Graphics",
          "Color & Typography Guidance",
          "Analytics Setup for Ads",
          "Basic Event Tracking",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced Banner Designs",
          "Multi-Platform Ads",
          "Animated Ad Graphics",
          "Ad Copy Suggestions",
          "Campaign Performance Tips",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full Ad Campaign Creative Suite",
          "Custom Animated Ads",
          "Video Ad Production",
          "Ongoing Ad Support & Optimization",
        ],
      },
    },
  },
  {
    id: 15,
    slug: "graphics-design",
    serviceSlug: "brand-identity-design",
    category: "Brand Identity Design",
    title: "Brand Identity Design",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Logo Concept Design",
          "Brand Color Palette",
          "Typography Selection",
          "Basic Stationery Design",
          "Brand Guidelines Overview",
          "Social Media Avatar",
          "Business Card Template",
          "Basic Analytics Setup",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Comprehensive Brand Guidelines",
          "Multiple Logo Variations",
          "Letterhead & Envelope Design",
          "Social Media Kit",
          "Marketing Collateral Design",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full Brand Identity Package",
          "Custom Iconography",
          "Website Branding Elements",
          "Ongoing Brand Support",
        ],
      },
    },
  },
  {
    id: 16,
    slug: "graphics-design",
    serviceSlug: "social-media-design",
    category: "Social Media Posts & Banners",
    title: "Social Media Posts & Banners",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Social Media Post Templates",
          "Banner Design for Ads",
          "Instagram Story Design",
          "Facebook Post Design",
          "Basic Animation Elements",
          "Brand Colors Applied",
          "Typography Consistency",
          "Basic Analytics Setup",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced Post & Banner Design",
          "Animated Social Media Creatives",
          "Multi-Platform Templates",
          "Engagement Optimization",
          "Performance Monitoring",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full Social Media Creative Suite",
          "Custom Video Content",
          "Campaign Optimization Support",
          "Ongoing Creative Management",
        ],
      },
    },
  },
  {
    id: 17,
    slug: "app-development",
    serviceSlug: "android-app",
    category: "Android App",
    title: "Android App",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Basic App UI Design",
          "Simple Navigation Setup",
          "Core Feature Integration",
          "Basic Authentication",
          "Responsive Layout",
          "Basic Analytics Setup",
          "Error Handling Implementation",
          "App Store Submission Guidance",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced UI/UX Design",
          "Push Notifications Integration",
          "Backend API Integration",
          "Multi-Screen Navigation",
          "Performance Optimization",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full App Development Suite",
          "Advanced Features & Animations",
          "Offline Functionality",
          "Post-Launch Maintenance Support",
        ],
      },
    },
  },
  {
    id: 18,
    slug: "app-development",
    serviceSlug: "ios-app",
    category: "iOS App",
    title: "iOS App",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Basic App UI Design",
          "Simple Navigation Setup",
          "Core Feature Integration",
          "Basic Authentication",
          "Responsive Layout",
          "Basic Analytics Setup",
          "Error Handling Implementation",
          "App Store Submission Guidance",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced UI/UX Design",
          "Push Notifications Integration",
          "Backend API Integration",
          "Multi-Screen Navigation",
          "Performance Optimization",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full App Development Suite",
          "Advanced Features & Animations",
          "Offline Functionality",
          "Post-Launch Maintenance Support",
        ],
      },
    },
  },
  {
    id: 19,
    slug: "app-development",
    serviceSlug: "web-app",
    category: "Web App",
    title: "Web App",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Basic UI Design",
          "Core Functionality Integration",
          "Responsive Layout",
          "Basic Authentication",
          "Frontend Validation Setup",
          "Basic Analytics Setup",
          "Error Handling Implementation",
          "Deployment Guidance",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced UI/UX Design",
          "API Integration",
          "Multi-Page Navigation",
          "Performance Optimization",
          "User Role Management",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full-Stack Development",
          "Security Hardening",
          "Offline Support & Caching",
          "Post-Launch Maintenance Support",
        ],
      },
    },
  },
  {
    id: 20,
    slug: "app-development",
    serviceSlug: "desktop-app",
    category: "Desktop App",
    title: "Desktop App",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Basic UI Design",
          "Core Feature Integration",
          "Responsive Layout",
          "Basic Authentication",
          "Frontend Validation Setup",
          "Basic Analytics Setup",
          "Error Handling Implementation",
          "Initial Setup & Deployment Guidance",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Advanced UI/UX Design",
          "API & Database Integration",
          "Multi-Window Navigation",
          "Performance Optimization",
          "User Roles & Permissions Setup",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full-Stack Desktop App Development",
          "Security Hardening",
          "Offline Support & Caching",
          "Post-Launch Maintenance & Support",
        ],
      },
    },
  },
  {
    id: 21,
    slug: "tracking-analytics",
    serviceSlug: "google-tag-manager",
    category: "Google Tag Manager",
    title: "Google Tag Manager",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Google Analytics Setup",
          "Basic Event Tracking",
          "Tag Installation & Configuration",
          "Pageview Tracking",
          "Click Tracking Setup",
          "Form Submission Tracking",
          "Basic Custom Variables",
          "Initial Debugging & Testing",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Enhanced Ecommerce Tracking",
          "Cross-Domain Tracking",
          "Custom Triggers & Variables",
          "Event Debugging & QA",
          "Tag Performance Optimization",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full GTM Implementation & Audit",
          "Custom Data Layer Development",
          "Integration with Marketing Tools",
          "Ongoing Support & Maintenance",
        ],
      },
    },
  },
  {
    id: 22,
    slug: "tracking-analytics",
    serviceSlug: "meta-pixel-conversion-api",
    category: "Meta Pixel Conversion API",
    title: "Meta Pixel Conversion API",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Pixel Installation & Setup",
          "Basic Event Tracking",
          "Pageview Tracking",
          "Click Event Setup",
          "Form Submission Tracking",
          "Custom Event Creation",
          "Initial Debugging & Testing",
          "Basic Reporting Setup",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Enhanced Event Mapping",
          "Cross-Domain Pixel Setup",
          "Custom Triggers & Variables",
          "Event QA & Debugging",
          "Integration with Ads Manager",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full Pixel Audit & Setup",
          "Custom Data Layer Implementation",
          "Integration with Marketing Tools",
          "Ongoing Support & Optimization",
        ],
      },
    },
  },
  {
    id: 23,
    slug: "tracking-analytics",
    serviceSlug: "google-analytics",
    category: "Google Analytics",
    title: "Google Analytics",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Google Analytics Account Setup",
          "Basic Event Tracking",
          "Pageview Tracking",
          "Click Tracking Setup",
          "Form Submission Tracking",
          "Goal Setup",
          "Initial Reporting Dashboard",
          "Basic Debugging & QA",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Enhanced Ecommerce Tracking",
          "Cross-Domain Tracking",
          "Custom Reports & Dashboards",
          "Event QA & Debugging",
          "Integration with Marketing Tools",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full GA Audit & Setup",
          "Custom Data Layer Development",
          "Integration with Ads & Marketing Tools",
          "Ongoing Support & Optimization",
        ],
      },
    },
  },
  {
    id: 24,
    slug: "tracking-analytics",
    serviceSlug: "server-side-tracking",
    category: "Server Side Tracking",
    title: "Server Side Tracking",
    pricing: {
      basic: {
        name: "Basic",
        price: "$199",
        deliveryTime: "3 Days",
        revisions: "2 Revisions",
        features: [
          "Google Analytics Account Setup",
          "Basic Event Tracking",
          "Pageview Tracking",
          "Form Submission Tracking",
          "Click Tracking Setup",
          "Goal Setup",
          "Initial Reporting Dashboard",
          "Basic Debugging & QA",
        ],
      },
      standard: {
        name: "Standard",
        price: "$299",
        deliveryTime: "5 Days",
        revisions: "4 Revisions",
        features: [
          "GA4 + GTM Setup",
          "Conversion Tracking",
          "Custom Events",
          "Enhanced Ecommerce Tracking",
          "Cross-Domain Tracking",
          "Custom Reports & Dashboards",
          "Event QA & Debugging",
          "Integration with Marketing Tools",
        ],
      },
      premium: {
        name: "Premium",
        price: "$499",
        deliveryTime: "7 Days",
        revisions: "Unlimited Revisions",
        features: [
          "Server-Side Tracking Implementation",
          "Meta CAPI Integration",
          "Advanced Analytics Reporting",
          "Data Accuracy Optimization",
          "Full GA Audit & Setup",
          "Custom Data Layer Development",
          "Integration with Ads & Marketing Tools",
          "Ongoing Support & Optimization",
        ],
      },
    },
  },
];

export default PricingData;
